#############################################################################
# Makefile for building: libhdbextractor++.so.1.0.0
# Generated by qmake (3.0) (Qt 5.3.2)
# Project:  hdbextractor.pro
# Template: lib
# Command: /usr/local/qt5/bin/qmake -o Makefile hdbextractor.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DHDBEXTRACTOR_VERSION_STR="\"1.0.0\"" -DHDBEXTRACTOR_VERSION=0x010000 -DVER_MAJ=1 -DVER_MIN=0 -DVER_FIX=0 -DHDBEXTRACTORLIB_PRINTINFO -DHDBEXTRACTOR_LIBRARY
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -g -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I/usr/local/qt5/mkspecs/linux-g++ -I. -Imysql/src -Idb/src -Idb -Isrc -I../src -Idb/src/helpers -Iutils -Iutils/private
LINK          = g++
LFLAGS        = -shared -Wl,-soname,libhdbextractor++.so.1
LIBS          = $(SUBLIBS) -lmysqlclient -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/local/qt5/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = src/hdbextractor.cpp \
		src/hdbextractorprivate.cpp \
		mysql/src/mysqlconnection.cpp \
		db/src/row.cpp \
		mysql/src/mysqlresult.cpp \
		mysql/src/mysqlrow.cpp \
		db/src/result.cpp \
		db/src/xvariant.cpp \
		hdb/src/mysqlhdbschema.cpp \
		db/src/xvariantlist.cpp \
		hdbpp/src/mysqlhdbppschema.cpp \
		src/configurationparser.cpp \
		src/queryconfiguration.cpp \
		db/src/configurabledbschema.cpp \
		db/src/helpers/configurabledbschemahelper.cpp \
		utils/datasiever.cpp \
		utils/private/datasieverprivate.cpp \
		utils/xvariantprinter.cpp \
		utils/datasieverprogresslistener.cpp \
		db/src/timeinterval.cpp \
		db/src/datetimeutils.cpp \
		db/src/xvariantprivate.cpp 
OBJECTS       = hdbextractor.o \
		hdbextractorprivate.o \
		mysqlconnection.o \
		row.o \
		mysqlresult.o \
		mysqlrow.o \
		result.o \
		xvariant.o \
		mysqlhdbschema.o \
		xvariantlist.o \
		mysqlhdbppschema.o \
		configurationparser.o \
		queryconfiguration.o \
		configurabledbschema.o \
		configurabledbschemahelper.o \
		datasiever.o \
		datasieverprivate.o \
		xvariantprinter.o \
		datasieverprogresslistener.o \
		timeinterval.o \
		datetimeutils.o \
		xvariantprivate.o
DIST          = /usr/local/qt5/mkspecs/features/spec_pre.prf \
		/usr/local/qt5/mkspecs/common/shell-unix.conf \
		/usr/local/qt5/mkspecs/common/unix.conf \
		/usr/local/qt5/mkspecs/common/linux.conf \
		/usr/local/qt5/mkspecs/common/gcc-base.conf \
		/usr/local/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/local/qt5/mkspecs/common/g++-base.conf \
		/usr/local/qt5/mkspecs/common/g++-unix.conf \
		/usr/local/qt5/mkspecs/qconfig.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_bluetooth.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_clucene_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_declarative.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_declarative_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_designer.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_designer_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_enginio.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_enginio_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_help.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_help_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_multimedia_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_nfc.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_nfc_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_positioning.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_positioning_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_qml.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_qmltest_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_quick.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_script.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_script_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_scripttools.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_scripttools_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_sensors.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_sensors_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_serialport.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_serialport_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_svg.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_svg_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_uitools.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_uitools_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_webkit.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_webkit_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_websockets.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_websockets_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_x11extras.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_x11extras_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/usr/local/qt5/mkspecs/features/qt_functions.prf \
		/usr/local/qt5/mkspecs/features/qt_config.prf \
		/usr/local/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/local/qt5/mkspecs/features/spec_post.prf \
		/usr/local/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/local/qt5/mkspecs/features/default_pre.prf \
		/usr/local/qt5/mkspecs/features/resolve_config.prf \
		/usr/local/qt5/mkspecs/features/default_post.prf \
		/usr/local/qt5/mkspecs/features/warn_on.prf \
		/usr/local/qt5/mkspecs/features/qt.prf \
		/usr/local/qt5/mkspecs/features/unix/thread.prf \
		/usr/local/qt5/mkspecs/features/testcase_targets.prf \
		/usr/local/qt5/mkspecs/features/exceptions.prf \
		/usr/local/qt5/mkspecs/features/yacc.prf \
		/usr/local/qt5/mkspecs/features/lex.prf \
		hdbextractor.pro src/hdbextractor.cpp \
		src/hdbextractorprivate.cpp \
		mysql/src/mysqlconnection.cpp \
		db/src/row.cpp \
		mysql/src/mysqlresult.cpp \
		mysql/src/mysqlrow.cpp \
		db/src/result.cpp \
		db/src/xvariant.cpp \
		hdb/src/mysqlhdbschema.cpp \
		db/src/xvariantlist.cpp \
		hdbpp/src/mysqlhdbppschema.cpp \
		src/configurationparser.cpp \
		src/queryconfiguration.cpp \
		db/src/configurabledbschema.cpp \
		db/src/helpers/configurabledbschemahelper.cpp \
		utils/datasiever.cpp \
		utils/private/datasieverprivate.cpp \
		utils/xvariantprinter.cpp \
		utils/datasieverprogresslistener.cpp \
		db/src/timeinterval.cpp \
		db/src/datetimeutils.cpp \
		db/src/xvariantprivate.cpp
QMAKE_TARGET  = hdbextractor++
DESTDIR       = #avoid trailing-slash linebreak
TARGET        = libhdbextractor++.so.1.0.0
TARGETA       = libhdbextractor++.a
TARGET0       = libhdbextractor++.so
TARGETD       = libhdbextractor++.so.1.0.0
TARGET1       = libhdbextractor++.so.1
TARGET2       = libhdbextractor++.so.1.0


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile  $(TARGET)

$(TARGET):  $(OBJECTS) $(SUBLIBS) $(OBJCOMP)  
	-$(DEL_FILE) $(TARGET) $(TARGET0) $(TARGET1) $(TARGET2)
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(LIBS) $(OBJCOMP)
	-ln -s $(TARGET) $(TARGET0)
	-ln -s $(TARGET) $(TARGET1)
	-ln -s $(TARGET) $(TARGET2)



staticlib: $(TARGETA)

$(TARGETA):  $(OBJECTS) $(OBJCOMP) 
	-$(DEL_FILE) $(TARGETA) 
	$(AR) $(TARGETA) $(OBJECTS)

Makefile: hdbextractor.pro /usr/local/qt5/mkspecs/linux-g++/qmake.conf /usr/local/qt5/mkspecs/features/spec_pre.prf \
		/usr/local/qt5/mkspecs/common/shell-unix.conf \
		/usr/local/qt5/mkspecs/common/unix.conf \
		/usr/local/qt5/mkspecs/common/linux.conf \
		/usr/local/qt5/mkspecs/common/gcc-base.conf \
		/usr/local/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/local/qt5/mkspecs/common/g++-base.conf \
		/usr/local/qt5/mkspecs/common/g++-unix.conf \
		/usr/local/qt5/mkspecs/qconfig.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_bluetooth.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_clucene_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_declarative.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_declarative_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_designer.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_designer_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_enginio.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_enginio_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_help.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_help_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_multimedia_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_nfc.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_nfc_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_positioning.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_positioning_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_qml.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_qmltest_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_quick.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_script.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_script_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_scripttools.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_scripttools_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_sensors.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_sensors_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_serialport.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_serialport_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_svg.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_svg_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_uitools.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_uitools_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_webkit.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_webkit_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_websockets.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_websockets_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_x11extras.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_x11extras_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/usr/local/qt5/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/usr/local/qt5/mkspecs/features/qt_functions.prf \
		/usr/local/qt5/mkspecs/features/qt_config.prf \
		/usr/local/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/local/qt5/mkspecs/features/spec_post.prf \
		/usr/local/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/local/qt5/mkspecs/features/default_pre.prf \
		/usr/local/qt5/mkspecs/features/resolve_config.prf \
		/usr/local/qt5/mkspecs/features/default_post.prf \
		/usr/local/qt5/mkspecs/features/warn_on.prf \
		/usr/local/qt5/mkspecs/features/qt.prf \
		/usr/local/qt5/mkspecs/features/unix/thread.prf \
		/usr/local/qt5/mkspecs/features/testcase_targets.prf \
		/usr/local/qt5/mkspecs/features/exceptions.prf \
		/usr/local/qt5/mkspecs/features/yacc.prf \
		/usr/local/qt5/mkspecs/features/lex.prf \
		hdbextractor.pro
	$(QMAKE) -o Makefile hdbextractor.pro
/usr/local/qt5/mkspecs/features/spec_pre.prf:
/usr/local/qt5/mkspecs/common/shell-unix.conf:
/usr/local/qt5/mkspecs/common/unix.conf:
/usr/local/qt5/mkspecs/common/linux.conf:
/usr/local/qt5/mkspecs/common/gcc-base.conf:
/usr/local/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/local/qt5/mkspecs/common/g++-base.conf:
/usr/local/qt5/mkspecs/common/g++-unix.conf:
/usr/local/qt5/mkspecs/qconfig.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_bluetooth.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_bluetooth_private.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_clucene_private.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_declarative.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_declarative_private.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_designer.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_designer_private.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_designercomponents_private.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_enginio.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_enginio_private.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_help.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_help_private.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_multimedia.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_multimedia_private.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_nfc.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_nfc_private.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_platformsupport_private.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_positioning.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_positioning_private.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_qml.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_qml_private.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_qmltest.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_qmltest_private.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_quick.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_quick_private.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_quickparticles_private.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_quickwidgets.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_script.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_script_private.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_scripttools.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_scripttools_private.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_sensors.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_sensors_private.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_serialport.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_serialport_private.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_svg.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_svg_private.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_uitools.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_uitools_private.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_webkit.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_webkit_private.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_webkitwidgets.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_webkitwidgets_private.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_websockets.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_websockets_private.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_x11extras.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_x11extras_private.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_xmlpatterns.pri:
/usr/local/qt5/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/usr/local/qt5/mkspecs/features/qt_functions.prf:
/usr/local/qt5/mkspecs/features/qt_config.prf:
/usr/local/qt5/mkspecs/linux-g++/qmake.conf:
/usr/local/qt5/mkspecs/features/spec_post.prf:
/usr/local/qt5/mkspecs/features/exclusive_builds.prf:
/usr/local/qt5/mkspecs/features/default_pre.prf:
/usr/local/qt5/mkspecs/features/resolve_config.prf:
/usr/local/qt5/mkspecs/features/default_post.prf:
/usr/local/qt5/mkspecs/features/warn_on.prf:
/usr/local/qt5/mkspecs/features/qt.prf:
/usr/local/qt5/mkspecs/features/unix/thread.prf:
/usr/local/qt5/mkspecs/features/testcase_targets.prf:
/usr/local/qt5/mkspecs/features/exceptions.prf:
/usr/local/qt5/mkspecs/features/yacc.prf:
/usr/local/qt5/mkspecs/features/lex.prf:
hdbextractor.pro:
qmake: FORCE
	@$(QMAKE) -o Makefile hdbextractor.pro

qmake_all: FORCE

dist: 
	@test -d .tmp/hdbextractor++1.0.0 || mkdir -p .tmp/hdbextractor++1.0.0
	$(COPY_FILE) --parents $(DIST) .tmp/hdbextractor++1.0.0/ && (cd `dirname .tmp/hdbextractor++1.0.0` && $(TAR) hdbextractor++1.0.0.tar hdbextractor++1.0.0 && $(COMPRESS) hdbextractor++1.0.0.tar) && $(MOVE) `dirname .tmp/hdbextractor++1.0.0`/hdbextractor++1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/hdbextractor++1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) $(TARGET0) $(TARGET1) $(TARGET2) $(TARGETA)
	-$(DEL_FILE) Makefile


####### Sub-libraries

check: first

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: 

####### Compile

hdbextractor.o: src/hdbextractor.cpp src/hdbextractor.h \
		db/src/xvariantlist.h \
		db/src/xvariant.h \
		db/src/resultlistenerinterface.h \
		src/hdbextractorprivate.h \
		mysql/src/mysqlconnection.h \
		db/src/connection.h \
		db/src/result.h \
		db/src/row.h \
		src/hdbxmacros.h \
		hdb/src/mysqlhdbschema.h \
		db/src/configurabledbschema.h \
		db/src/dbschema.h \
		db/src/helpers/configurabledbschemahelper.h \
		hdbpp/src/mysqlhdbppschema.h \
		src/hdbextractorlistener.h \
		src/queryconfiguration.h \
		db/src/timeinterval.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o hdbextractor.o src/hdbextractor.cpp

hdbextractorprivate.o: src/hdbextractorprivate.cpp src/hdbextractorprivate.h \
		src/hdbextractor.h \
		db/src/xvariantlist.h \
		db/src/xvariant.h \
		db/src/resultlistenerinterface.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o hdbextractorprivate.o src/hdbextractorprivate.cpp

mysqlconnection.o: mysql/src/mysqlconnection.cpp mysql/src/mysqlconnection.h \
		db/src/connection.h \
		mysql/src/mysqlresult.h \
		db/src/result.h \
		db/src/row.h \
		mysql/src/mysqlrow.h \
		db/src/xvariant.h \
		src/hdbxmacros.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mysqlconnection.o mysql/src/mysqlconnection.cpp

row.o: db/src/row.cpp db/src/row.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o row.o db/src/row.cpp

mysqlresult.o: mysql/src/mysqlresult.cpp mysql/src/mysqlresult.h \
		db/src/result.h \
		db/src/row.h \
		mysql/src/mysqlrow.h \
		src/hdbxmacros.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mysqlresult.o mysql/src/mysqlresult.cpp

mysqlrow.o: mysql/src/mysqlrow.cpp mysql/src/mysqlrow.h \
		db/src/row.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mysqlrow.o mysql/src/mysqlrow.cpp

result.o: db/src/result.cpp db/src/result.h \
		db/src/row.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o result.o db/src/result.cpp

xvariant.o: db/src/xvariant.cpp db/src/xvariant.h \
		src/hdbxmacros.h \
		db/src/datetimeutils.h \
		db/src/xvariantprivate.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o xvariant.o db/src/xvariant.cpp

mysqlhdbschema.o: hdb/src/mysqlhdbschema.cpp hdb/src/mysqlhdbschema.h \
		db/src/configurabledbschema.h \
		db/src/dbschema.h \
		db/src/helpers/configurabledbschemahelper.h \
		db/src/xvariantlist.h \
		db/src/xvariant.h \
		db/src/resultlistenerinterface.h \
		db/src/connection.h \
		db/src/row.h \
		db/src/result.h \
		mysql/src/mysqlconnection.h \
		src/hdbxmacros.h \
		db/src/dbschemaprivate.h \
		db/src/timeinterval.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mysqlhdbschema.o hdb/src/mysqlhdbschema.cpp

xvariantlist.o: db/src/xvariantlist.cpp db/src/xvariantlist.h \
		db/src/xvariant.h \
		src/hdbxmacros.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o xvariantlist.o db/src/xvariantlist.cpp

mysqlhdbppschema.o: hdbpp/src/mysqlhdbppschema.cpp hdbpp/src/mysqlhdbppschema.h \
		db/src/configurabledbschema.h \
		db/src/dbschema.h \
		db/src/helpers/configurabledbschemahelper.h \
		db/src/xvariantlist.h \
		db/src/xvariant.h \
		db/src/resultlistenerinterface.h \
		db/src/connection.h \
		db/src/row.h \
		db/src/result.h \
		mysql/src/mysqlconnection.h \
		src/hdbxmacros.h \
		db/src/dbschemaprivate.h \
		db/src/timeinterval.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mysqlhdbppschema.o hdbpp/src/mysqlhdbppschema.cpp

configurationparser.o: src/configurationparser.cpp src/configurationparser.h \
		src/hdbxmacros.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o configurationparser.o src/configurationparser.cpp

queryconfiguration.o: src/queryconfiguration.cpp src/queryconfiguration.h \
		src/configurationparser.h \
		src/hdbxmacros.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o queryconfiguration.o src/queryconfiguration.cpp

configurabledbschema.o: db/src/configurabledbschema.cpp db/src/configurabledbschema.h \
		db/src/dbschema.h \
		db/src/dbschemaprivate.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o configurabledbschema.o db/src/configurabledbschema.cpp

configurabledbschemahelper.o: db/src/helpers/configurabledbschemahelper.cpp db/src/helpers/configurabledbschemahelper.h \
		src/queryconfiguration.h \
		src/hdbxmacros.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o configurabledbschemahelper.o db/src/helpers/configurabledbschemahelper.cpp

datasiever.o: utils/datasiever.cpp utils/datasiever.h \
		db/src/xvariant.h \
		utils/private/datasieverprivate.h \
		utils/xvariantprinter.h \
		src/hdbxmacros.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o datasiever.o utils/datasiever.cpp

datasieverprivate.o: utils/private/datasieverprivate.cpp utils/private/datasieverprivate.h \
		db/src/xvariant.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o datasieverprivate.o utils/private/datasieverprivate.cpp

xvariantprinter.o: utils/xvariantprinter.cpp utils/xvariantprinter.h \
		db/src/xvariant.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o xvariantprinter.o utils/xvariantprinter.cpp

datasieverprogresslistener.o: utils/datasieverprogresslistener.cpp utils/datasieverprogresslistener.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o datasieverprogresslistener.o utils/datasieverprogresslistener.cpp

timeinterval.o: db/src/timeinterval.cpp db/src/timeinterval.h \
		db/src/datetimeutils.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o timeinterval.o db/src/timeinterval.cpp

datetimeutils.o: db/src/datetimeutils.cpp db/src/datetimeutils.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o datetimeutils.o db/src/datetimeutils.cpp

xvariantprivate.o: db/src/xvariantprivate.cpp db/src/xvariantprivate.h \
		db/src/xvariant.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o xvariantprivate.o db/src/xvariantprivate.cpp

####### Install

install_lib: first FORCE
	@test -d $(INSTALL_ROOT)/runtime/lib || mkdir -p $(INSTALL_ROOT)/runtime/lib
	ln -sf libhdbextractor++.so.1.0.0 /runtime/lib/libhdbextractor++.so.1 && ln -sf libhdbextractor++.so.1 /runtime/lib/libhdbextractor++.so
	-$(INSTALL_PROGRAM) /home/giacomo/devel/utils/hdbextractor/trunk/libhdbextractor++.so.1.0.0 $(INSTALL_ROOT)/runtime/lib/

uninstall_lib: FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/runtime/lib/libhdbextractor++.so.1.0.0
	-$(DEL_DIR) $(INSTALL_ROOT)/runtime/lib/ 


install_inc: first FORCE
	@test -d $(INSTALL_ROOT)/runtime/include/hdbextractor || mkdir -p $(INSTALL_ROOT)/runtime/include/hdbextractor
	-$(INSTALL_FILE) /home/giacomo/devel/utils/hdbextractor/trunk/src/hdbextractor.h $(INSTALL_ROOT)/runtime/include/hdbextractor/
	-$(INSTALL_FILE) /home/giacomo/devel/utils/hdbextractor/trunk/src/hdbextractorprivate.h $(INSTALL_ROOT)/runtime/include/hdbextractor/
	-$(INSTALL_FILE) /home/giacomo/devel/utils/hdbextractor/trunk/src/hdbxmacros.h $(INSTALL_ROOT)/runtime/include/hdbextractor/
	-$(INSTALL_FILE) /home/giacomo/devel/utils/hdbextractor/trunk/db/src/connection.h $(INSTALL_ROOT)/runtime/include/hdbextractor/
	-$(INSTALL_FILE) /home/giacomo/devel/utils/hdbextractor/trunk/mysql/src/mysqlconnection.h $(INSTALL_ROOT)/runtime/include/hdbextractor/
	-$(INSTALL_FILE) /home/giacomo/devel/utils/hdbextractor/trunk/db/src/row.h $(INSTALL_ROOT)/runtime/include/hdbextractor/
	-$(INSTALL_FILE) /home/giacomo/devel/utils/hdbextractor/trunk/mysql/src/mysqlresult.h $(INSTALL_ROOT)/runtime/include/hdbextractor/
	-$(INSTALL_FILE) /home/giacomo/devel/utils/hdbextractor/trunk/db/src/result.h $(INSTALL_ROOT)/runtime/include/hdbextractor/
	-$(INSTALL_FILE) /home/giacomo/devel/utils/hdbextractor/trunk/mysql/src/mysqlrow.h $(INSTALL_ROOT)/runtime/include/hdbextractor/
	-$(INSTALL_FILE) /home/giacomo/devel/utils/hdbextractor/trunk/db/src/xvariant.h $(INSTALL_ROOT)/runtime/include/hdbextractor/
	-$(INSTALL_FILE) /home/giacomo/devel/utils/hdbextractor/trunk/db/src/dbschema.h $(INSTALL_ROOT)/runtime/include/hdbextractor/
	-$(INSTALL_FILE) /home/giacomo/devel/utils/hdbextractor/trunk/db/src/dbschemaprivate.h $(INSTALL_ROOT)/runtime/include/hdbextractor/
	-$(INSTALL_FILE) /home/giacomo/devel/utils/hdbextractor/trunk/hdb/src/mysqlhdbschema.h $(INSTALL_ROOT)/runtime/include/hdbextractor/
	-$(INSTALL_FILE) /home/giacomo/devel/utils/hdbextractor/trunk/db/src/xvariantlist.h $(INSTALL_ROOT)/runtime/include/hdbextractor/
	-$(INSTALL_FILE) /home/giacomo/devel/utils/hdbextractor/trunk/db/src/xvariantprivate.h $(INSTALL_ROOT)/runtime/include/hdbextractor/
	-$(INSTALL_FILE) /home/giacomo/devel/utils/hdbextractor/trunk/db/src/resultlistenerinterface.h $(INSTALL_ROOT)/runtime/include/hdbextractor/
	-$(INSTALL_FILE) /home/giacomo/devel/utils/hdbextractor/trunk/src/hdbextractorlistener.h $(INSTALL_ROOT)/runtime/include/hdbextractor/
	-$(INSTALL_FILE) /home/giacomo/devel/utils/hdbextractor/trunk/hdbpp/src/mysqlhdbppschema.h $(INSTALL_ROOT)/runtime/include/hdbextractor/
	-$(INSTALL_FILE) /home/giacomo/devel/utils/hdbextractor/trunk/src/configurationparser.h $(INSTALL_ROOT)/runtime/include/hdbextractor/
	-$(INSTALL_FILE) /home/giacomo/devel/utils/hdbextractor/trunk/src/queryconfiguration.h $(INSTALL_ROOT)/runtime/include/hdbextractor/
	-$(INSTALL_FILE) /home/giacomo/devel/utils/hdbextractor/trunk/db/src/configurabledbschema.h $(INSTALL_ROOT)/runtime/include/hdbextractor/
	-$(INSTALL_FILE) /home/giacomo/devel/utils/hdbextractor/trunk/db/src/helpers/configurabledbschemahelper.h $(INSTALL_ROOT)/runtime/include/hdbextractor/
	-$(INSTALL_FILE) /home/giacomo/devel/utils/hdbextractor/trunk/utils/datasiever.h $(INSTALL_ROOT)/runtime/include/hdbextractor/
	-$(INSTALL_FILE) /home/giacomo/devel/utils/hdbextractor/trunk/utils/private/datasieverprivate.h $(INSTALL_ROOT)/runtime/include/hdbextractor/
	-$(INSTALL_FILE) /home/giacomo/devel/utils/hdbextractor/trunk/utils/xvariantprinter.h $(INSTALL_ROOT)/runtime/include/hdbextractor/
	-$(INSTALL_FILE) /home/giacomo/devel/utils/hdbextractor/trunk/utils/datasieverprogresslistener.h $(INSTALL_ROOT)/runtime/include/hdbextractor/
	-$(INSTALL_FILE) /home/giacomo/devel/utils/hdbextractor/trunk/db/src/timeinterval.h $(INSTALL_ROOT)/runtime/include/hdbextractor/
	-$(INSTALL_FILE) /home/giacomo/devel/utils/hdbextractor/trunk/db/src/datetimeutils.h $(INSTALL_ROOT)/runtime/include/hdbextractor/

uninstall_inc: FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/runtime/include/hdbextractor/datetimeutils.h
	-$(DEL_FILE) -r $(INSTALL_ROOT)/runtime/include/hdbextractor/timeinterval.h
	-$(DEL_FILE) -r $(INSTALL_ROOT)/runtime/include/hdbextractor/datasieverprogresslistener.h
	-$(DEL_FILE) -r $(INSTALL_ROOT)/runtime/include/hdbextractor/xvariantprinter.h
	-$(DEL_FILE) -r $(INSTALL_ROOT)/runtime/include/hdbextractor/datasieverprivate.h
	-$(DEL_FILE) -r $(INSTALL_ROOT)/runtime/include/hdbextractor/datasiever.h
	-$(DEL_FILE) -r $(INSTALL_ROOT)/runtime/include/hdbextractor/configurabledbschemahelper.h
	-$(DEL_FILE) -r $(INSTALL_ROOT)/runtime/include/hdbextractor/configurabledbschema.h
	-$(DEL_FILE) -r $(INSTALL_ROOT)/runtime/include/hdbextractor/queryconfiguration.h
	-$(DEL_FILE) -r $(INSTALL_ROOT)/runtime/include/hdbextractor/configurationparser.h
	-$(DEL_FILE) -r $(INSTALL_ROOT)/runtime/include/hdbextractor/mysqlhdbppschema.h
	-$(DEL_FILE) -r $(INSTALL_ROOT)/runtime/include/hdbextractor/hdbextractorlistener.h
	-$(DEL_FILE) -r $(INSTALL_ROOT)/runtime/include/hdbextractor/resultlistenerinterface.h
	-$(DEL_FILE) -r $(INSTALL_ROOT)/runtime/include/hdbextractor/xvariantprivate.h
	-$(DEL_FILE) -r $(INSTALL_ROOT)/runtime/include/hdbextractor/xvariantlist.h
	-$(DEL_FILE) -r $(INSTALL_ROOT)/runtime/include/hdbextractor/mysqlhdbschema.h
	-$(DEL_FILE) -r $(INSTALL_ROOT)/runtime/include/hdbextractor/dbschemaprivate.h
	-$(DEL_FILE) -r $(INSTALL_ROOT)/runtime/include/hdbextractor/dbschema.h
	-$(DEL_FILE) -r $(INSTALL_ROOT)/runtime/include/hdbextractor/xvariant.h
	-$(DEL_FILE) -r $(INSTALL_ROOT)/runtime/include/hdbextractor/mysqlrow.h
	-$(DEL_FILE) -r $(INSTALL_ROOT)/runtime/include/hdbextractor/result.h
	-$(DEL_FILE) -r $(INSTALL_ROOT)/runtime/include/hdbextractor/mysqlresult.h
	-$(DEL_FILE) -r $(INSTALL_ROOT)/runtime/include/hdbextractor/row.h
	-$(DEL_FILE) -r $(INSTALL_ROOT)/runtime/include/hdbextractor/mysqlconnection.h
	-$(DEL_FILE) -r $(INSTALL_ROOT)/runtime/include/hdbextractor/connection.h
	-$(DEL_FILE) -r $(INSTALL_ROOT)/runtime/include/hdbextractor/hdbxmacros.h
	-$(DEL_FILE) -r $(INSTALL_ROOT)/runtime/include/hdbextractor/hdbextractorprivate.h
	-$(DEL_FILE) -r $(INSTALL_ROOT)/runtime/include/hdbextractor/hdbextractor.h
	-$(DEL_DIR) $(INSTALL_ROOT)/runtime/include/hdbextractor/ 


install_doc: first FORCE
	@test -d $(INSTALL_ROOT)/runtime/share/doc/hdbextractor || mkdir -p $(INSTALL_ROOT)/runtime/share/doc/hdbextractor
	doxygen Doxyfile;
	-$(INSTALL_DIR) /home/giacomo/devel/utils/hdbextractor/trunk/doc $(INSTALL_ROOT)/runtime/share/doc/hdbextractor/

uninstall_doc: FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/runtime/share/doc/hdbextractor/doc
	-$(DEL_DIR) $(INSTALL_ROOT)/runtime/share/doc/hdbextractor/ 


install:  install_lib install_inc install_doc  FORCE

uninstall: uninstall_lib uninstall_inc uninstall_doc   FORCE

FORCE:

