#ifndef HDBEXTRACTORQT_GLOBAL_H
#define HDBEXTRACTORQT_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(HDBEXTRACTORQT_LIBRARY)
#  define HDBEXTRACTORQTSHARED_EXPORT Q_DECL_EXPORT
#else
#  define HDBEXTRACTORQTSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // HDBEXTRACTORQT_GLOBAL_H
